[package]
name = "oat"
version = "0.1.0"
edition = "2021"
authors = ["Paul Artjomow <me@prixix.com / paul-artjomow@hotmail.com>"]
repository = "https://github.com/Prixix/oat"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
